CREATE TABLE  "AIRCRAFT" 
   (	"AIRCRAFTID" NUMBER, 
	"NAME" VARCHAR2(40), 
	"CAPACITY" NUMBER, 
	 PRIMARY KEY ("AIRCRAFTID") ENABLE
   ) ;CREATE TABLE  "FLIGHT" 
   (	"FLIGHTID" NUMBER(*,0), 
	"DEPARTURE" VARCHAR2(40), 
	"DESTINATION" VARCHAR2(40), 
	"DEPARTURE_TIME" TIMESTAMP (6), 
	"ARRIVAL_TIME" TIMESTAMP (6), 
	"AIRCRAFTID" NUMBER(*,0), 
	"STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("FLIGHTID") ENABLE
   ) ;CREATE TABLE  "USER_TABLE" 
   (	"USERID" NUMBER(*,0), 
	"USERTYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50), 
	"PASSWORD" VARCHAR2(50) NOT NULL ENABLE, 
	"PHONE_NUMBER" NUMBER, 
	"CNIC" NUMBER, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("USERID") ENABLE
   ) ;CREATE TABLE  "BAGGAGE_HANDLING" 
   (	"BAGGAGEID" NUMBER(*,0), 
	"PASSENGERID" NUMBER(*,0), 
	"FLIGHTID" NUMBER(*,0), 
	"STATUS" VARCHAR2(50), 
	"LOCATION" VARCHAR2(100), 
	 PRIMARY KEY ("BAGGAGEID") ENABLE
   ) ;CREATE TABLE  "BOOKINGS" 
   (	"BOOKINGID" NUMBER NOT NULL ENABLE, 
	"PASSENGERID" NUMBER NOT NULL ENABLE, 
	"FLIGHTID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BOOKINGS_PK" PRIMARY KEY ("BOOKINGID") ENABLE
   ) ;CREATE TABLE  "FEEDBACK" 
   (	"FEEDBACKID" NUMBER, 
	"USERID" NUMBER NOT NULL ENABLE, 
	"FEEDBACK_DETAILS" VARCHAR2(200), 
	"RATING" NUMBER(2,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("FEEDBACKID") ENABLE
   ) ;CREATE TABLE  "FLIGHT_PRICES" 
   (	"FLIGHTID" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER, 
	 CONSTRAINT "FLIGHT_PRICES_PK" PRIMARY KEY ("FLIGHTID") ENABLE
   ) ;CREATE TABLE  "MAINTENANCE" 
   (	"MAINTENANCEID" NUMBER(*,0), 
	"AIRCRAFTID" NUMBER(*,0), 
	"TASK_DESCRIPTION" VARCHAR2(100), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("MAINTENANCEID") ENABLE
   ) ;CREATE TABLE  "PASSENGER_SERVICES" 
   (	"SERVICEID" NUMBER(*,0), 
	"PASSENGERID" NUMBER(*,0), 
	"FLIGHTID" NUMBER(*,0), 
	"SERVICE_TYPE" VARCHAR2(50), 
	"SERVICE_DETAILS" VARCHAR2(100), 
	"SERVICE_TIME" TIMESTAMP (6), 
	 PRIMARY KEY ("SERVICEID") ENABLE
   ) ;CREATE TABLE  "REPORTS_ANALYTICS" 
   (	"REPORTID" NUMBER(*,0), 
	"REPORT_TYPE" VARCHAR2(50), 
	"GENERATED_DATE" DATE, 
	"DETAILS" VARCHAR2(100), 
	"ANALYSIS" VARCHAR2(100), 
	 PRIMARY KEY ("REPORTID") ENABLE
   ) ;CREATE TABLE  "REVENUE" 
   (	"REVENUEID" NUMBER(*,0), 
	"TRANSACTION_DATE" DATE, 
	"AMOUNT" NUMBER, 
	"SOURCE" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(100), 
	 PRIMARY KEY ("REVENUEID") ENABLE
   ) ;CREATE TABLE  "SAFETY_COMPLIANCE" 
   (	"SAFETYID" NUMBER(*,0), 
	"EVENT_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(100), 
	"SEVERITY" VARCHAR2(50), 
	"RESOLUTION" VARCHAR2(100), 
	 PRIMARY KEY ("SAFETYID") ENABLE
   ) ;CREATE TABLE  "TASKS" 
   (	"TASKID" NUMBER, 
	"EMP_ID" NUMBER NOT NULL ENABLE, 
	"TASK_DETAILS" VARCHAR2(200), 
	"DUE_DATE" DATE, 
	"TASK_STATUS" VARCHAR2(20) DEFAULT 'In Progress', 
	 PRIMARY KEY ("TASKID") ENABLE
   ) ;ALTER TABLE  "BOOKINGS" ADD CONSTRAINT "BOOKINGS_FK" FOREIGN KEY ("PASSENGERID")
	  REFERENCES  "USER_TABLE" ("USERID") ENABLE;ALTER TABLE  "FLIGHT_PRICES" ADD CONSTRAINT "FLIGHT_PRICES_FK" FOREIGN KEY ("FLIGHTID")
	  REFERENCES  "FLIGHT" ("FLIGHTID") ENABLE;ALTER TABLE  "TASKS" ADD FOREIGN KEY ("EMP_ID")
	  REFERENCES  "USER_TABLE" ("USERID") ENABLE;ALTER TABLE  "FLIGHT" ADD FOREIGN KEY ("AIRCRAFTID")
	  REFERENCES  "AIRCRAFT" ("AIRCRAFTID") ENABLE;ALTER TABLE  "PASSENGER_SERVICES" ADD FOREIGN KEY ("PASSENGERID")
	  REFERENCES  "USER_TABLE" ("USERID") ENABLE;ALTER TABLE  "PASSENGER_SERVICES" ADD FOREIGN KEY ("FLIGHTID")
	  REFERENCES  "FLIGHT" ("FLIGHTID") ENABLE;ALTER TABLE  "MAINTENANCE" ADD FOREIGN KEY ("AIRCRAFTID")
	  REFERENCES  "AIRCRAFT" ("AIRCRAFTID") ENABLE;ALTER TABLE  "FEEDBACK" ADD FOREIGN KEY ("USERID")
	  REFERENCES  "USER_TABLE" ("USERID") ENABLE;ALTER TABLE  "BOOKINGS" ADD FOREIGN KEY ("FLIGHTID")
	  REFERENCES  "FLIGHT" ("FLIGHTID") ENABLE;ALTER TABLE  "BAGGAGE_HANDLING" ADD FOREIGN KEY ("PASSENGERID")
	  REFERENCES  "USER_TABLE" ("USERID") ENABLE;ALTER TABLE  "BAGGAGE_HANDLING" ADD FOREIGN KEY ("FLIGHTID")
	  REFERENCES  "FLIGHT" ("FLIGHTID") ENABLE;