-- 10 Aircraft Insertions
INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (1, 'Boeing 737', 200);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (2, 'Airbus A320', 180);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (3, 'Boeing 777', 350);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (4, 'Embraer E190', 100);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (5, 'Airbus A380', 500);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (6, 'Bombardier CRJ700', 70);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (7, 'Cessna Citation', 8);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (8, 'Gulfstream G650', 14);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (9, 'McDonnell Douglas MD-80', 150);

INSERT INTO "AIRCRAFT" ("AIRCRAFTID", "NAME", "CAPACITY") 
VALUES (10, 'Bombardier Global 7500', 19);