-- 10 Feedback Insertions
INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (301, 1001, 'Great service!', 5);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (302, 1002, 'Smooth flight.', 4);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (303, 1003, 'Delayed departure but good staff.', 3);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (304, 1004, 'Clean cabin and comfortable seats.', 4);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (305, 1005, 'Helpful crew.', 5);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (306, 1006, 'Good in-flight entertainment.', 4);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (307, 1007, 'Baggage delayed.', 2);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (308, 1008, 'Friendly staff.', 5);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (309, 1009, 'Smooth check-in process.', 4);

INSERT INTO "FEEDBACK" ("FEEDBACKID", "USERID", "FEEDBACK_DETAILS", "RATING") 
VALUES (310, 1010, 'Good food options.', 4);
